export const FIRE_VERIFICATION_MODEL_VERSION = '1.0.0'
export const FIRE_VERIFICATION_METHOD_CATALOG_VERSION = '1.0.0'

export const FIRE_VERIFICATION_THRESHOLDS = {
  notRequiredMaxVerificationScore: 25,
  notRequiredMaxLevel: 'useful',
  highUncertaintyMinScore: 40,
  actionCapUnlockMinVerification: 35,
  recentActivityWindowHours: 12,
  persistenceAssessmentWindowHours: 48,
  spatialExtentStaleHours: 24,
  evidenceDecayUrgentHours: 36,
  resolutionVerifyWindowHours: 72,
} as const

export const PLAN_PRIORITY_WEIGHTS = {
  verification_score: 0.35,
  urgency: 0.25,
  evidence_decay: 0.2,
  action_unlock: 0.1,
  lifecycle: 0.1,
} as const

export const METHOD_RANKING_WEIGHTS = {
  relevance: 0.25,
  information_gain: 0.2,
  urgency_fit: 0.2,
  cost_efficiency: 0.1,
  availability: 0.1,
  evidence_strength: 0.15,
} as const

export const COST_BAND_SCORE: Record<string, number> = {
  negligible: 1,
  low: 0.85,
  medium: 0.6,
  high: 0.35,
  unknown: 0.5,
}

export const TIME_BAND_URGENCY_FIT: Record<string, number> = {
  minutes: 1,
  hours: 0.9,
  same_day: 0.75,
  multi_day: 0.45,
  unknown: 0.5,
}

export const AVAILABILITY_SCORE: Record<string, number> = {
  available: 1,
  limited: 0.65,
  unavailable: 0,
  unknown: 0.4,
}

import type { VerificationMethodDef, VerificationNeedDef } from '@/modules/verification/verification.types'

export const FIRE_VERIFICATION_NEED_DEFS: Record<string, VerificationNeedDef> = {
  confirm_recent_activity: {
    need_type: 'confirm_recent_activity',
    question: '¿Existe actividad térmica reciente correlacionada con el incidente?',
    evidence_minimum: [
      'Detección térmica nueva dentro de la ventana configurada',
      'O evidencia de campo suficientemente fuerte y georreferenciada',
    ],
    success_criteria: 'Detección correlacionada reciente o evidencia visual compatible',
    inconclusive_criteria: 'Sin nueva detección pero cobertura o frecuencia de observación insuficiente',
    failure_criteria: 'Fuente no disponible durante la ventana',
    default_window_hours: 12,
  },
  assess_event_persistence: {
    need_type: 'assess_event_persistence',
    question: '¿La señal térmica muestra persistencia sostenida o variación temporal relevante?',
    evidence_minimum: ['Serie temporal de detecciones', 'Patrón de repetición dentro de ventana'],
    success_criteria: 'Persistencia o declinación documentada con serie temporal',
    inconclusive_criteria: 'Detecciones insuficientes para evaluar persistencia',
    failure_criteria: 'Sin acceso a serie temporal',
    default_window_hours: 48,
  },
  assess_spatial_extent: {
    need_type: 'assess_spatial_extent',
    question: '¿Cuál es la extensión territorial aproximada de la señal?',
    evidence_minimum: ['Distribución espacial de detecciones', 'Estimación conservadora de área'],
    success_criteria: 'Extensión estimada con método documentado',
    inconclusive_criteria: 'Detecciones puntuales sin dispersión suficiente',
    failure_criteria: 'Sin geometría utilizable',
    default_window_hours: 24,
  },
  obtain_visual_ground_evidence: {
    need_type: 'obtain_visual_ground_evidence',
    question: '¿Existe evidencia visual compatible con quema o actividad visible?',
    evidence_minimum: [
      'Fotografía georreferenciada',
      'Fecha y hora',
      'Descripción estructurada',
      'Indicación de humo, llama, área afectada o ausencia visible',
    ],
    success_criteria: 'Evidencia visual georreferenciada con descripción estructurada',
    inconclusive_criteria: 'Observación parcial o condiciones que limitan visibilidad',
    failure_criteria: 'Sin acceso al área o negativa de observación sin cobertura alternativa',
    default_window_hours: 48,
  },
  clarify_land_cover_context: {
    need_type: 'clarify_land_cover_context',
    question: '¿Cuál es el contexto de cobertura del suelo en el área de la señal?',
    evidence_minimum: ['Clasificación de cobertura', 'Fuente y resolución documentadas'],
    success_criteria: 'Contexto de cobertura completado o parcialmente completado con limitaciones',
    inconclusive_criteria: 'Cobertura parcial con incertidumbre significativa',
    failure_criteria: 'Fuente de cobertura no disponible',
    default_window_hours: 72,
  },
  clarify_protected_area_relationship: {
    need_type: 'clarify_protected_area_relationship',
    question: '¿Cuál es la relación espacial con áreas protegidas cercanas o superpuestas?',
    evidence_minimum: ['Geometría de área protegida', 'Distancia o intersección documentada'],
    success_criteria: 'Relación espacial clarificada',
    inconclusive_criteria: 'Geometría protegida parcial o desactualizada',
    failure_criteria: 'Capa de áreas protegidas no disponible',
    default_window_hours: 72,
  },
  improve_population_context: {
    need_type: 'improve_population_context',
    question: '¿El contexto de población cercana es suficientemente preciso para evaluar exposición?',
    evidence_minimum: ['Estimación poblacional en buffer', 'Nivel de confianza documentado'],
    success_criteria: 'Contexto poblacional con confianza aceptable',
    inconclusive_criteria: 'Divergencia entre fuentes o cobertura parcial',
    failure_criteria: 'Fuentes poblacionales no disponibles',
    default_window_hours: 72,
  },
  differentiate_possible_non_fire_heat_source: {
    need_type: 'differentiate_possible_non_fire_heat_source',
    question: '¿La señal podría corresponder a una fuente térmica no vegetal conocida?',
    evidence_minimum: ['Cruce con fuentes térmicas conocidas', 'Contexto land cover y actividad humana'],
    success_criteria: 'Fuente alternativa descartada o identificada con evidencia',
    inconclusive_criteria: 'Evidencia insuficiente para distinguir',
    failure_criteria: 'Sin catálogo de fuentes alternativas',
    default_window_hours: 48,
  },
  verify_incident_resolution: {
    need_type: 'verify_incident_resolution',
    question: '¿La ausencia reciente de señal respalda el cierre operacional del incidente?',
    evidence_minimum: [
      'Ventana sin detecciones dentro del umbral',
      'Sin evidencia contradictoria reciente',
    ],
    success_criteria: 'Ventana de inactividad completada sin nueva señal correlacionada',
    inconclusive_criteria: 'Cobertura insuficiente para confirmar ausencia de actividad',
    failure_criteria: 'Nueva detección correlacionada durante la ventana',
    default_window_hours: 72,
  },
  verify_reactivation: {
    need_type: 'verify_reactivation',
    question: '¿Una nueva señal correlacionada requiere reabrir la evaluación del incidente?',
    evidence_minimum: ['Nueva detección correlacionada', 'Compatibilidad temporal y espacial'],
    success_criteria: 'Reactivación documentada con detección correlacionada',
    inconclusive_criteria: 'Señal débil o fuera de ventana de reactivación',
    failure_criteria: 'Señal descartada como no correlacionada',
    default_window_hours: 24,
  },
}

export const FIRE_VERIFICATION_METHOD_CATALOG: VerificationMethodDef[] = [
  {
    method_id: 'review_latest_thermal_detections',
    method_type: 'remote_analytical',
    label: 'Revisión de detecciones térmicas recientes',
    supported_need_types: ['confirm_recent_activity', 'assess_event_persistence', 'verify_reactivation'],
    expected_information_gain: 0.7,
    estimated_cost_band: 'negligible',
    estimated_time_band: 'minutes',
    requires_field_presence: false,
    requires_human_review: true,
    requires_external_provider: false,
    availability_status: 'available',
    evidence_strength: 0.55,
    geographic_constraints: [],
    weather_constraints: [],
    safety_constraints: [],
    prerequisites: [],
    limitations: ['No confirma incendio; solo actividad térmica satelital'],
  },
  {
    method_id: 'review_time_series',
    method_type: 'remote_analytical',
    label: 'Revisión de serie temporal',
    supported_need_types: ['assess_event_persistence', 'confirm_recent_activity', 'verify_incident_resolution'],
    expected_information_gain: 0.75,
    estimated_cost_band: 'negligible',
    estimated_time_band: 'hours',
    requires_field_presence: false,
    requires_human_review: true,
    requires_external_provider: false,
    availability_status: 'available',
    evidence_strength: 0.6,
    geographic_constraints: [],
    weather_constraints: [],
    safety_constraints: [],
    prerequisites: [],
    limitations: ['Depende de frecuencia de paso satelital'],
  },
  {
    method_id: 'request_new_satellite_observation',
    method_type: 'remote_analytical',
    label: 'Solicitar nueva observación satelital',
    supported_need_types: ['confirm_recent_activity', 'assess_spatial_extent'],
    expected_information_gain: 0.65,
    estimated_cost_band: 'low',
    estimated_time_band: 'hours',
    requires_field_presence: false,
    requires_human_review: false,
    requires_external_provider: true,
    availability_status: 'limited',
    evidence_strength: 0.55,
    geographic_constraints: [],
    weather_constraints: ['nubosidad puede limitar'],
    safety_constraints: [],
    prerequisites: [],
    limitations: ['No garantiza cobertura inmediata'],
  },
  {
    method_id: 'request_higher_resolution_imagery',
    method_type: 'remote_analytical',
    label: 'Solicitar imagen de mayor resolución',
    supported_need_types: ['assess_spatial_extent', 'obtain_visual_ground_evidence'],
    expected_information_gain: 0.8,
    estimated_cost_band: 'medium',
    estimated_time_band: 'same_day',
    requires_field_presence: false,
    requires_human_review: true,
    requires_external_provider: true,
    availability_status: 'limited',
    evidence_strength: 0.7,
    geographic_constraints: [],
    weather_constraints: ['nubosidad'],
    safety_constraints: [],
    prerequisites: [],
    limitations: ['Puede no estar disponible en ventana corta'],
  },
  {
    method_id: 'review_land_cover_sources',
    method_type: 'remote_analytical',
    label: 'Revisar fuentes de cobertura del suelo',
    supported_need_types: ['clarify_land_cover_context', 'differentiate_possible_non_fire_heat_source'],
    expected_information_gain: 0.7,
    estimated_cost_band: 'negligible',
    estimated_time_band: 'hours',
    requires_field_presence: false,
    requires_human_review: true,
    requires_external_provider: false,
    availability_status: 'available',
    evidence_strength: 0.65,
    geographic_constraints: [],
    weather_constraints: [],
    safety_constraints: [],
    prerequisites: [],
    limitations: ['Resolución y fecha de cobertura pueden limitar precisión'],
  },
  {
    method_id: 'review_protected_area_geometry',
    method_type: 'remote_analytical',
    label: 'Revisar geometría de áreas protegidas',
    supported_need_types: ['clarify_protected_area_relationship'],
    expected_information_gain: 0.75,
    estimated_cost_band: 'negligible',
    estimated_time_band: 'hours',
    requires_field_presence: false,
    requires_human_review: true,
    requires_external_provider: false,
    availability_status: 'available',
    evidence_strength: 0.7,
    geographic_constraints: [],
    weather_constraints: [],
    safety_constraints: [],
    prerequisites: [],
    limitations: [],
  },
  {
    method_id: 'review_population_model',
    method_type: 'remote_analytical',
    label: 'Revisar modelo de población',
    supported_need_types: ['improve_population_context'],
    expected_information_gain: 0.7,
    estimated_cost_band: 'negligible',
    estimated_time_band: 'hours',
    requires_field_presence: false,
    requires_human_review: true,
    requires_external_provider: false,
    availability_status: 'available',
    evidence_strength: 0.6,
    geographic_constraints: [],
    weather_constraints: [],
    safety_constraints: [],
    prerequisites: [],
    limitations: ['Modelos raster pueden divergir de datos administrativos'],
  },
  {
    method_id: 'cross_check_known_heat_sources',
    method_type: 'remote_analytical',
    label: 'Cruzar con fuentes térmicas conocidas',
    supported_need_types: ['differentiate_possible_non_fire_heat_source'],
    expected_information_gain: 0.65,
    estimated_cost_band: 'low',
    estimated_time_band: 'hours',
    requires_field_presence: false,
    requires_human_review: true,
    requires_external_provider: false,
    availability_status: 'limited',
    evidence_strength: 0.6,
    geographic_constraints: [],
    weather_constraints: [],
    safety_constraints: [],
    prerequisites: [],
    limitations: ['Catálogo de fuentes alternativas puede estar incompleto'],
  },
  {
    method_id: 'request_local_authority_confirmation',
    method_type: 'remote_human',
    label: 'Solicitar confirmación a autoridad local',
    supported_need_types: ['obtain_visual_ground_evidence', 'confirm_recent_activity'],
    expected_information_gain: 0.75,
    estimated_cost_band: 'low',
    estimated_time_band: 'same_day',
    requires_field_presence: false,
    requires_human_review: true,
    requires_external_provider: true,
    availability_status: 'limited',
    evidence_strength: 0.75,
    geographic_constraints: [],
    weather_constraints: [],
    safety_constraints: [],
    prerequisites: [],
    limitations: ['Depende de disponibilidad institucional'],
  },
  {
    method_id: 'request_protected_area_staff_observation',
    method_type: 'remote_human',
    label: 'Solicitar observación de personal de área protegida',
    supported_need_types: ['obtain_visual_ground_evidence', 'clarify_protected_area_relationship'],
    expected_information_gain: 0.8,
    estimated_cost_band: 'low',
    estimated_time_band: 'same_day',
    requires_field_presence: false,
    requires_human_review: true,
    requires_external_provider: true,
    availability_status: 'limited',
    evidence_strength: 0.8,
    geographic_constraints: ['requiere área protegida identificada'],
    weather_constraints: [],
    safety_constraints: [],
    prerequisites: ['clarify_protected_area_relationship'],
    limitations: ['No convierte ausencia visual en prueba absoluta'],
  },
  {
    method_id: 'request_structured_citizen_report',
    method_type: 'remote_human',
    label: 'Solicitar reporte ciudadano estructurado',
    supported_need_types: ['obtain_visual_ground_evidence'],
    expected_information_gain: 0.55,
    estimated_cost_band: 'negligible',
    estimated_time_band: 'hours',
    requires_field_presence: false,
    requires_human_review: true,
    requires_external_provider: true,
    availability_status: 'limited',
    evidence_strength: 0.5,
    geographic_constraints: [],
    weather_constraints: [],
    safety_constraints: [],
    prerequisites: [],
    limitations: ['Calidad variable; requiere validación'],
  },
  {
    method_id: 'field_visual_inspection',
    method_type: 'field',
    label: 'Inspección visual de campo',
    supported_need_types: ['obtain_visual_ground_evidence', 'assess_spatial_extent', 'differentiate_possible_non_fire_heat_source'],
    expected_information_gain: 0.85,
    estimated_cost_band: 'medium',
    estimated_time_band: 'same_day',
    requires_field_presence: true,
    requires_human_review: true,
    requires_external_provider: false,
    availability_status: 'available',
    evidence_strength: 0.85,
    geographic_constraints: ['acceso terrestre'],
    weather_constraints: ['visibilidad', 'condiciones de acceso'],
    safety_constraints: ['evaluar riesgo antes de desplazamiento'],
    prerequisites: [],
    limitations: ['No convierte ausencia visual en prueba absoluta'],
  },
  {
    method_id: 'georeferenced_photo_collection',
    method_type: 'field',
    label: 'Recolección de fotografía georreferenciada',
    supported_need_types: ['obtain_visual_ground_evidence', 'assess_spatial_extent'],
    expected_information_gain: 0.9,
    estimated_cost_band: 'medium',
    estimated_time_band: 'same_day',
    requires_field_presence: true,
    requires_human_review: true,
    requires_external_provider: false,
    availability_status: 'available',
    evidence_strength: 0.9,
    geographic_constraints: ['acceso terrestre'],
    weather_constraints: ['visibilidad'],
    safety_constraints: ['evaluar riesgo'],
    prerequisites: [],
    limitations: [],
  },
  {
    method_id: 'drone_observation',
    method_type: 'field',
    label: 'Observación con dron',
    supported_need_types: ['obtain_visual_ground_evidence', 'assess_spatial_extent'],
    expected_information_gain: 0.88,
    estimated_cost_band: 'high',
    estimated_time_band: 'same_day',
    requires_field_presence: true,
    requires_human_review: true,
    requires_external_provider: false,
    availability_status: 'limited',
    evidence_strength: 0.88,
    geographic_constraints: ['restricciones de vuelo'],
    weather_constraints: ['viento', 'visibilidad'],
    safety_constraints: ['autorización de vuelo'],
    prerequisites: [],
    limitations: ['Requiere operador y equipo'],
  },
]
