import type { NeedResolutionStatus } from '@/modules/verification/resolution/verification-resolution.types'

export const RESOLUTION_MODEL_VERSION = '1.0.0'

export const DOWNSTREAM_EFFECTS = [
  'finding_reevaluation_requested',
  'priority_reevaluation_requested',
  'lifecycle_reevaluation_requested',
  'incident_reevaluation_requested',
  'verification_replanning_requested',
] as const

export const MATERIAL_RESOLUTION_STATUSES: NeedResolutionStatus[] = [
  'satisfied',
  'partially_satisfied',
  'conflicting_evidence',
]

export const CRITICAL_LIMITATION_MARKERS = [
  'crítica',
  'critical',
  'sin geolocalización',
  'resolución baja',
  'ventana temporal',
]

/** Fixtures sintéticos — solo pruebas */
export const SYNTHETIC_RESOLUTION_FIXTURES = {
  need_visual: {
    need_id: 'need-visual',
    need_type: 'obtain_visual_ground_evidence',
    need_question: '¿Existe evidencia visual compatible?',
    need_priority: 80,
    recommended_window_hours: 48,
  },
  need_activity: {
    need_id: 'need-activity',
    need_type: 'confirm_recent_activity',
    need_question: '¿Existe actividad térmica reciente?',
    need_priority: 90,
    recommended_window_hours: 12,
  },
  strong_visual_evidence: {
    submission_id: 'sub-strong',
    validation_id: 'val-strong',
    evidence_type: 'structured_observation',
    validation_status: 'accepted',
    evidence_strength: 'strong',
    overall_quality_score: 82,
    temporal_relevance_score: 88,
    spatial_relevance_score: 85,
    source_independence_score: 75,
    submitted_by_id: 'user-a',
    source_type: 'mission_user',
    source_device: 'phone-1',
    captured_at: '2026-07-10T10:00:00.000Z',
    verification_need_id: 'need-visual',
    requirement_ids: ['req-obs'],
    valid_coverage_status: 'valid_coverage',
    limitations: [],
    observation: {
      visible_smoke: 'yes',
      visible_flame: 'uncertain',
      observation_distance_m: 150,
      visibility_conditions: 'clara',
    },
  },
  limited_evidence: {
    submission_id: 'sub-limited',
    validation_id: 'val-limited',
    evidence_type: 'georeferenced_photo',
    validation_status: 'accepted_with_limitations',
    evidence_strength: 'moderate',
    overall_quality_score: 58,
    temporal_relevance_score: 45,
    spatial_relevance_score: 50,
    source_independence_score: 70,
    submitted_by_id: 'user-b',
    source_type: 'mission_user',
    source_device: 'phone-2',
    captured_at: '2026-07-10T09:00:00.000Z',
    verification_need_id: 'need-visual',
    requirement_ids: ['req-photo'],
    valid_coverage_status: 'valid_partial_coverage',
    limitations: ['Metadata temporal incompleta', 'Precisión GPS baja'],
    observation: null,
  },
  irrelevant_evidence: {
    submission_id: 'sub-irrelevant',
    validation_id: 'val-irrelevant',
    evidence_type: 'external_document',
    validation_status: 'accepted',
    evidence_strength: 'strong',
    overall_quality_score: 90,
    temporal_relevance_score: 80,
    spatial_relevance_score: 20,
    source_independence_score: 80,
    submitted_by_id: 'user-c',
    source_type: 'institution',
    source_device: null,
    captured_at: '2026-07-10T08:00:00.000Z',
    verification_need_id: null,
    requirement_ids: [],
    valid_coverage_status: 'invalid_coverage',
    limitations: [],
    observation: null,
  },
  independent_b: {
    submission_id: 'sub-ind-b',
    validation_id: 'val-ind-b',
    evidence_type: 'structured_observation',
    validation_status: 'accepted',
    evidence_strength: 'moderate',
    overall_quality_score: 72,
    temporal_relevance_score: 80,
    spatial_relevance_score: 78,
    source_independence_score: 85,
    submitted_by_id: 'user-d',
    source_type: 'institution',
    source_device: null,
    captured_at: '2026-07-10T11:00:00.000Z',
    verification_need_id: 'need-visual',
    requirement_ids: ['req-obs'],
    valid_coverage_status: 'valid_coverage',
    limitations: [],
    observation: { visible_smoke: 'yes' },
  },
  negative_limited: {
    submission_id: 'sub-neg',
    validation_id: 'val-neg',
    evidence_type: 'structured_observation',
    validation_status: 'accepted_with_limitations',
    evidence_strength: 'low',
    overall_quality_score: 55,
    temporal_relevance_score: 70,
    spatial_relevance_score: 60,
    source_independence_score: 70,
    submitted_by_id: 'user-e',
    source_type: 'mission_user',
    source_device: 'phone-3',
    captured_at: '2026-07-10T16:00:00.000Z',
    verification_need_id: 'need-visual',
    requirement_ids: ['req-obs'],
    valid_coverage_status: 'valid_partial_coverage',
    limitations: ['Observación negativa con alcance local limitado'],
    observation: {
      visible_smoke: 'no',
      visible_flame: 'no',
      observation_distance_m: 400,
    },
  },
  mission_completed_no_evidence: {
    mission_id: 'mission-empty',
    status: 'completed',
    mission_type: 'field_visual_inspection',
    verification_need_id: 'need-visual',
    completed_at: '2026-07-10T12:00:00.000Z',
  },
  material_conflict: {
    submission_id_a: 'sub-smoke-yes',
    submission_id_b: 'sub-smoke-no',
    conflict_type: 'observation_contradiction',
    conflict_field: 'visible_smoke',
    description: 'Contradicción en visible_smoke',
    captured_at_a: '2026-07-10T10:00:00.000Z',
    captured_at_b: '2026-07-10T16:00:00.000Z',
  },
}
