export const FIRE_MISSION_PROFILE_VERSION = '1.0.0'

export const FIRE_MISSION_DOMAIN = 'fire'

export const MISSION_INITIAL_STATUS: 'draft' | 'ready' = 'ready'

export const MISSION_ACTIVE_STATUSES = [
  'draft',
  'ready',
  'approved',
  'in_progress',
  'blocked',
] as const

export const METHOD_TO_MISSION_TYPE: Record<string, string> = {
  review_latest_thermal_detections: 'remote_analytical_review',
  review_time_series: 'remote_analytical_review',
  request_new_satellite_observation: 'satellite_reobservation_request',
  request_higher_resolution_imagery: 'higher_resolution_imagery_review',
  review_land_cover_sources: 'remote_analytical_review',
  review_protected_area_geometry: 'remote_analytical_review',
  review_population_model: 'remote_analytical_review',
  cross_check_known_heat_sources: 'remote_analytical_review',
  request_local_authority_confirmation: 'local_authority_confirmation_request',
  request_protected_area_staff_observation: 'protected_area_staff_observation',
  request_structured_citizen_report: 'structured_citizen_evidence_request',
  field_visual_inspection: 'field_visual_inspection',
  georeferenced_photo_collection: 'georeferenced_photo_collection',
  drone_observation: 'drone_observation',
}

export const MISSION_PRIORITY_WEIGHTS = {
  plan_priority: 0.5,
  evidence_decay: 0.25,
  method_urgency: 0.15,
  lifecycle: 0.1,
} as const

export const TIME_BAND_HOURS: Record<string, number> = {
  minutes: 1,
  hours: 6,
  same_day: 24,
  multi_day: 72,
  unknown: 48,
}

import type { MissionTemplateDef } from '@/modules/missions/missions.types'

const SHARED_FIELD_TASKS = [
  {
    task_type: 'navigate_to_area',
    sequence: 1,
    title: 'Llegar al área objetivo',
    instructions: 'Desplazarse al área indicada respetando restricciones de acceso y seguridad.',
    required: true,
    completion_criteria: 'Posición dentro del área objetivo o punto de observación seguro',
  },
  {
    task_type: 'record_gps_position',
    sequence: 2,
    title: 'Registrar posición GPS',
    instructions: 'Capturar coordenadas y hora de la observación.',
    required: true,
    completion_criteria: 'Coordenadas y timestamp registrados',
  },
  {
    task_type: 'structured_observation',
    sequence: 3,
    title: 'Realizar observación estructurada',
    instructions: 'Documentar indicadores visibles sin inferir confirmación de incendio.',
    required: true,
    completion_criteria: 'Observación estructurada completada',
  },
  {
    task_type: 'capture_georeferenced_photos',
    sequence: 4,
    title: 'Capturar fotografías georreferenciadas',
    instructions: 'Registrar imágenes con ubicación y orientación aproximada.',
    required: true,
    completion_criteria: 'Al menos una fotografía georreferenciada',
  },
  {
    task_type: 'record_visible_indicators',
    sequence: 5,
    title: 'Registrar indicadores visibles',
    instructions: 'Indicar humo, llama, área afectada o ausencia visible sin concluir extinción.',
    required: true,
    completion_criteria: 'Indicadores documentados de forma estructurada',
  },
  {
    task_type: 'submit_evidence',
    sequence: 6,
    title: 'Enviar evidencia',
    instructions: 'Entregar observación y archivos según requisitos de la misión.',
    required: true,
    completion_criteria: 'Evidencia mínima entregada o resultado inconcluso documentado',
  },
]

export const FIRE_MISSION_TEMPLATES: Record<string, MissionTemplateDef> = {
  remote_analytical_review: {
    mission_type: 'remote_analytical_review',
    title_template: 'Revisión analítica remota — {need_label}',
    objective_template: 'Revisar señal térmica y contexto para reducir incertidumbre sobre {need_question}',
    completion_criteria: 'Revisión documentada con hallazgos estructurados',
    inconclusive_criteria: 'Cobertura o datos insuficientes para concluir la revisión',
    blocking_conditions: ['Fuente analítica no disponible'],
    cancellation_conditions: ['Plan de verificación superseded o cancelado'],
    tasks: [
      {
        task_type: 'gather_inputs',
        sequence: 1,
        title: 'Recopilar insumos',
        instructions: 'Reunir detecciones, contexto y ventana temporal relevante.',
        required: true,
        completion_criteria: 'Insumos mínimos disponibles',
      },
      {
        task_type: 'perform_review',
        sequence: 2,
        title: 'Realizar revisión',
        instructions: 'Evaluar actividad reciente y consistencia sin afirmar incendio.',
        required: true,
        completion_criteria: 'Revisión completada con notas estructuradas',
      },
      {
        task_type: 'document_findings',
        sequence: 3,
        title: 'Documentar hallazgos',
        instructions: 'Registrar resultado compatible, incompatible o inconcluso.',
        required: true,
        completion_criteria: 'Hallazgos documentados',
      },
    ],
    evidence_requirements: [
      {
        evidence_type: 'time_series_review_result',
        required: true,
        minimum_count: 1,
        required_metadata: ['fecha', 'fuente', 'ventana'],
        quality_criteria: ['Referencias a detecciones correlacionadas'],
        acceptance_criteria: 'Resultado estructurado de revisión temporal o analítica',
      },
      {
        evidence_type: 'timestamped_note',
        required: true,
        minimum_count: 1,
        required_metadata: ['autor', 'fecha'],
        quality_criteria: ['Lenguaje operacional conservador'],
        acceptance_criteria: 'Nota con conclusión operacional sin copy prohibido',
      },
    ],
  },
  satellite_reobservation_request: {
    mission_type: 'satellite_reobservation_request',
    title_template: 'Solicitud de reobservación satelital — {need_label}',
    objective_template: 'Obtener nueva observación satelital para verificar actividad reciente',
    completion_criteria: 'Solicitud registrada y seguimiento de disponibilidad documentado',
    inconclusive_criteria: 'Sin cobertura satelital en la ventana operativa',
    blocking_conditions: ['Proveedor satelital no disponible'],
    cancellation_conditions: ['Ventana operativa expirada'],
    tasks: [
      {
        task_type: 'define_aoi',
        sequence: 1,
        title: 'Definir área de interés',
        instructions: 'Delimitar AOI basada en incidente y necesidad.',
        required: true,
        completion_criteria: 'AOI definida',
      },
      {
        task_type: 'submit_request',
        sequence: 2,
        title: 'Registrar solicitud',
        instructions: 'Documentar solicitud de nueva pasada o producto.',
        required: true,
        completion_criteria: 'Solicitud registrada',
      },
    ],
    evidence_requirements: [
      {
        evidence_type: 'satellite_review_result',
        required: true,
        minimum_count: 1,
        required_metadata: ['producto', 'fecha', 'cobertura'],
        quality_criteria: ['AOI documentada'],
        acceptance_criteria: 'Registro de solicitud o resultado de cobertura',
      },
    ],
  },
  field_visual_inspection: {
    mission_type: 'field_visual_inspection',
    title_template: 'Inspección visual de campo — {need_label}',
    objective_template: 'Realizar observación en terreno para recopilar evidencia visual estructurada',
    completion_criteria: 'Observación de campo completada con evidencia mínima',
    inconclusive_criteria: 'Condiciones de acceso o visibilidad impiden observación concluyente',
    blocking_conditions: ['Acceso restringido', 'Riesgo de seguridad no mitigado'],
    cancellation_conditions: ['Ventana expirada', 'Plan superseded'],
    tasks: SHARED_FIELD_TASKS,
    evidence_requirements: [
      {
        evidence_type: 'structured_observation',
        required: true,
        minimum_count: 1,
        required_metadata: ['fecha', 'ubicación', 'indicadores'],
        quality_criteria: ['Descripción estructurada'],
        acceptance_criteria: 'Observación estructurada con indicadores visibles',
      },
      {
        evidence_type: 'georeferenced_photo',
        required: true,
        minimum_count: 1,
        required_metadata: ['coordenadas', 'fecha', 'orientación'],
        quality_criteria: ['Georreferenciación válida'],
        acceptance_criteria: 'Al menos una fotografía georreferenciada',
      },
      {
        evidence_type: 'location_confirmation',
        required: true,
        minimum_count: 1,
        required_metadata: ['coordenadas'],
        quality_criteria: ['Consistencia con área objetivo'],
        acceptance_criteria: 'Ubicación confirmada en campo',
      },
    ],
  },
  georeferenced_photo_collection: {
    mission_type: 'georeferenced_photo_collection',
    title_template: 'Recolección fotográfica georreferenciada — {need_label}',
    objective_template: 'Capturar fotografías georreferenciadas para documentar indicadores visibles',
    completion_criteria: 'Set mínimo de fotografías georreferenciadas entregado',
    inconclusive_criteria: 'Visibilidad insuficiente para documentar indicadores',
    blocking_conditions: ['Acceso restringido'],
    cancellation_conditions: ['Ventana expirada'],
    tasks: SHARED_FIELD_TASKS,
    evidence_requirements: [
      {
        evidence_type: 'georeferenced_photo',
        required: true,
        minimum_count: 2,
        required_metadata: ['coordenadas', 'fecha'],
        quality_criteria: ['Resolución utilizable'],
        acceptance_criteria: 'Mínimo de fotografías georreferenciadas cumplido',
      },
    ],
  },
  drone_observation: {
    mission_type: 'drone_observation',
    title_template: 'Observación con dron — {need_label}',
    objective_template: 'Obtener observación aérea para evaluar extensión e indicadores visibles',
    completion_criteria: 'Vuelo completado con evidencia aérea mínima',
    inconclusive_criteria: 'Condiciones de vuelo o autorización impiden observación',
    blocking_conditions: ['Autorización de vuelo pendiente', 'Condiciones meteorológicas adversas'],
    cancellation_conditions: ['Ventana expirada'],
    tasks: [
      ...SHARED_FIELD_TASKS.slice(0, 3),
      {
        task_type: 'drone_flight',
        sequence: 4,
        title: 'Ejecutar vuelo de observación',
        instructions: 'Realizar vuelo conforme a restricciones y capturar imágenes.',
        required: true,
        completion_criteria: 'Vuelo completado con registro de trayectoria',
      },
      ...SHARED_FIELD_TASKS.slice(4),
    ],
    evidence_requirements: [
      {
        evidence_type: 'drone_image',
        required: true,
        minimum_count: 1,
        required_metadata: ['fecha', 'altitud', 'coordenadas'],
        quality_criteria: ['Cobertura del área objetivo'],
        acceptance_criteria: 'Imagen aérea utilizable',
      },
      {
        evidence_type: 'structured_observation',
        required: true,
        minimum_count: 1,
        required_metadata: ['fecha', 'indicadores'],
        quality_criteria: ['Descripción estructurada'],
        acceptance_criteria: 'Observación estructurada complementaria',
      },
    ],
  },
  local_authority_confirmation_request: {
    mission_type: 'local_authority_confirmation_request',
    title_template: 'Solicitud de confirmación institucional — {need_label}',
    objective_template: 'Solicitar confirmación o observación a autoridad local sobre actividad reciente',
    completion_criteria: 'Respuesta institucional registrada o seguimiento documentado',
    inconclusive_criteria: 'Sin respuesta en ventana operativa',
    blocking_conditions: ['Canal institucional no disponible'],
    cancellation_conditions: ['Ventana expirada'],
    tasks: [
      {
        task_type: 'prepare_request',
        sequence: 1,
        title: 'Preparar solicitud',
        instructions: 'Compilar ubicación, ventana y necesidad de verificación.',
        required: true,
        completion_criteria: 'Solicitud preparada',
      },
      {
        task_type: 'submit_request',
        sequence: 2,
        title: 'Enviar solicitud',
        instructions: 'Registrar solicitud a autoridad competente.',
        required: true,
        completion_criteria: 'Solicitud enviada',
      },
      {
        task_type: 'track_response',
        sequence: 3,
        title: 'Registrar seguimiento',
        instructions: 'Documentar respuesta o ausencia de respuesta en ventana.',
        required: true,
        completion_criteria: 'Seguimiento documentado',
      },
    ],
    evidence_requirements: [
      {
        evidence_type: 'institutional_response',
        required: false,
        minimum_count: 1,
        required_metadata: ['institución', 'fecha'],
        quality_criteria: ['Referencia a ubicación'],
        acceptance_criteria: 'Respuesta institucional o registro de no respuesta',
      },
    ],
  },
  protected_area_staff_observation: {
    mission_type: 'protected_area_staff_observation',
    title_template: 'Observación de personal de área protegida — {need_label}',
    objective_template: 'Solicitar observación de personal para recopilar evidencia visual',
    completion_criteria: 'Observación de personal registrada con evidencia mínima',
    inconclusive_criteria: 'Personal no disponible en ventana',
    blocking_conditions: ['Área protegida no identificada'],
    cancellation_conditions: ['Ventana expirada'],
    tasks: [
      {
        task_type: 'coordinate_staff',
        sequence: 1,
        title: 'Coordinar observación',
        instructions: 'Contactar personal de área protegida con ubicación y ventana.',
        required: true,
        completion_criteria: 'Coordinación registrada',
      },
      {
        task_type: 'collect_observation',
        sequence: 2,
        title: 'Recopilar observación',
        instructions: 'Obtener descripción estructurada e imágenes si disponibles.',
        required: true,
        completion_criteria: 'Observación recibida',
      },
    ],
    evidence_requirements: [
      {
        evidence_type: 'structured_observation',
        required: true,
        minimum_count: 1,
        required_metadata: ['fecha', 'ubicación'],
        quality_criteria: ['Indicadores visibles documentados'],
        acceptance_criteria: 'Observación estructurada de personal',
      },
      {
        evidence_type: 'georeferenced_photo',
        required: false,
        minimum_count: 1,
        required_metadata: ['coordenadas', 'fecha'],
        quality_criteria: ['Georreferenciación si aplica'],
        acceptance_criteria: 'Fotografía complementaria si disponible',
      },
    ],
  },
  structured_citizen_evidence_request: {
    mission_type: 'structured_citizen_evidence_request',
    title_template: 'Solicitud de reporte ciudadano estructurado — {need_label}',
    objective_template: 'Solicitar reporte ciudadano estructurado para evidencia visual complementaria',
    completion_criteria: 'Reporte recibido y validado mínimamente',
    inconclusive_criteria: 'Sin reportes en ventana',
    blocking_conditions: ['Canal ciudadano no disponible'],
    cancellation_conditions: ['Ventana expirada'],
    tasks: [
      {
        task_type: 'open_intake',
        sequence: 1,
        title: 'Abrir recepción estructurada',
        instructions: 'Publicar solicitud con campos mínimos requeridos.',
        required: true,
        completion_criteria: 'Recepción activa',
      },
      {
        task_type: 'validate_submission',
        sequence: 2,
        title: 'Validar envío',
        instructions: 'Revisar consistencia básica sin afirmar veracidad absoluta.',
        required: true,
        completion_criteria: 'Envío validado o descartado con razón',
      },
    ],
    evidence_requirements: [
      {
        evidence_type: 'structured_observation',
        required: true,
        minimum_count: 1,
        required_metadata: ['fecha', 'ubicación aproximada'],
        quality_criteria: ['Formato estructurado'],
        acceptance_criteria: 'Reporte ciudadano estructurado',
      },
    ],
  },
  higher_resolution_imagery_review: {
    mission_type: 'higher_resolution_imagery_review',
    title_template: 'Revisión de imagen de mayor resolución — {need_label}',
    objective_template: 'Obtener y revisar imagen de mayor resolución para evaluar extensión e indicadores',
    completion_criteria: 'Imagen revisada con notas estructuradas',
    inconclusive_criteria: 'Imagen no disponible en ventana',
    blocking_conditions: ['Proveedor de imagen no disponible'],
    cancellation_conditions: ['Ventana expirada'],
    tasks: [
      {
        task_type: 'request_imagery',
        sequence: 1,
        title: 'Solicitar imagen',
        instructions: 'Registrar solicitud de producto de mayor resolución.',
        required: true,
        completion_criteria: 'Solicitud registrada',
      },
      {
        task_type: 'review_imagery',
        sequence: 2,
        title: 'Revisar imagen',
        instructions: 'Evaluar extensión e indicadores visibles sin confirmar incendio.',
        required: true,
        completion_criteria: 'Revisión documentada',
      },
    ],
    evidence_requirements: [
      {
        evidence_type: 'satellite_review_result',
        required: true,
        minimum_count: 1,
        required_metadata: ['resolución', 'fecha'],
        quality_criteria: ['AOI cubierta'],
        acceptance_criteria: 'Resultado de revisión de imagen',
      },
    ],
  },
}

// Fallback template for unmapped methods
FIRE_MISSION_TEMPLATES.remote_analytical_review

export const NEED_TYPE_LABELS: Record<string, string> = {
  confirm_recent_activity: 'actividad reciente',
  assess_event_persistence: 'persistencia',
  assess_spatial_extent: 'extensión territorial',
  obtain_visual_ground_evidence: 'evidencia visual',
  clarify_land_cover_context: 'cobertura del suelo',
  clarify_protected_area_relationship: 'área protegida',
  improve_population_context: 'contexto poblacional',
  differentiate_possible_non_fire_heat_source: 'fuente térmica alternativa',
  verify_incident_resolution: 'cierre operacional',
  verify_reactivation: 'reactivación',
}
