/**
 * AUTO-GENERATED by `npm run event:sync`. DO NOT EDIT BY HAND.
 *
 * Single source of server-side plugin wiring: every plugin's server module is
 * imported here so its repository/detector/source register into the shared
 * server registry at startup. Importing this module has the side effect of
 * registration.
 */
import './rainfall-deficit.server.js'
import './synthetic-framework-test.server.js'
import './thermal-activity.server.js'
