/**
 * AUTO-GENERATED by `npm run event:sync`. DO NOT EDIT BY HAND.
 *
 * Single source of manifest registration: every plugin's `event.manifest.ts`
 * is discovered by convention (src/events/<type>/) and listed here. Static
 * imports keep this compatible with Vite, tsx and vitest alike.
 */
import type { EnvironmentalEventManifest } from '@/modules/environmental-events/manifest/event-manifest'
import syntheticFrameworkTestManifest from '@/events/synthetic-framework-test/event.manifest'
import thermalActivityManifest from '@/events/thermal-activity/event.manifest'

export const ALL_EVENT_MANIFESTS: EnvironmentalEventManifest[] = [
  syntheticFrameworkTestManifest,
  thermalActivityManifest,
]
