import type { TerramindPermission } from '@/core/auth/permissions'
import type { RateLimitProfile } from '../middleware/rate-limit.js'

export type RouteProtectionStatus = 'protected' | 'public-by-design' | 'incomplete'

export interface OperationalRouteSpec {
  method: string
  path: string
  resource: string
  permission: TerramindPermission | null
  authorizer: string | null
  tenantPath: string
  usesServiceRole: boolean
  rateLimit?: RateLimitProfile
  status: RouteProtectionStatus
  routeFile: string
}

export const OPERATIONAL_ROUTE_REGISTRY: OperationalRouteSpec[] = [
  // Intelligence — incidents
  {
    method: 'GET',
    path: '/api/intelligence/incidents',
    resource: 'incident',
    permission: 'incidents.view',
    authorizer: 'orgListScope',
    tenantPath: 'organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'incidents.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/incidents/:id',
    resource: 'incident',
    permission: 'incidents.view',
    authorizer: 'authorizeIncidentAccess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'incidents.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/incidents/:id/history',
    resource: 'incident',
    permission: 'incidents.view',
    authorizer: 'authorizeIncidentAccess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'incidents.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/incidents/:id/events',
    resource: 'incident',
    permission: 'incidents.view',
    authorizer: 'authorizeIncidentAccess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'incidents.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/incidents/:id/evidence',
    resource: 'evidence_submission',
    permission: 'evidence.view',
    authorizer: 'authorizeIncidentAccess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'evidence-intake.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/incidents/:id/missions',
    resource: 'mission',
    permission: 'missions.view',
    authorizer: 'authorizeIncidentAccess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'missions.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/incidents/:id/verification-plan',
    resource: 'verification_plan',
    permission: 'verification_plans.view',
    authorizer: 'authorizeIncidentAccess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'verification.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/incidents/:id/verification-needs',
    resource: 'verification_need',
    permission: 'verification_plans.view',
    authorizer: 'authorizeIncidentAccess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'verification.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/incidents/:id/verification-resolution',
    resource: 'verification_resolution',
    permission: 'verification_plans.view',
    authorizer: 'authorizeIncidentAccess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'verification-resolution.ts',
  },
  // Intelligence — findings
  {
    method: 'GET',
    path: '/api/intelligence/findings',
    resource: 'finding',
    permission: 'findings.view',
    authorizer: 'orgListScope',
    tenantPath: 'organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'findings.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/findings/:id',
    resource: 'finding',
    permission: 'findings.view',
    authorizer: 'authorizeFindingAccess',
    tenantPath: 'finding.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'findings.ts',
  },
  // Intelligence — priorities
  {
    method: 'GET',
    path: '/api/intelligence/priorities',
    resource: 'priority',
    permission: 'priorities.view',
    authorizer: 'orgListScope',
    tenantPath: 'organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'priorities.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/priorities/:id',
    resource: 'priority',
    permission: 'priorities.view',
    authorizer: 'authorizePriorityAccess',
    tenantPath: 'priority.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'priorities.ts',
  },
  // Intelligence — verification plans
  {
    method: 'GET',
    path: '/api/intelligence/verification-plans',
    resource: 'verification_plan',
    permission: 'verification_plans.view',
    authorizer: 'orgListScope',
    tenantPath: 'organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'verification.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/verification-plans/:id',
    resource: 'verification_plan',
    permission: 'verification_plans.view',
    authorizer: 'authorizeVerificationPlanAccess',
    tenantPath: 'verification_plan.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'verification.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/verification-plans/:id/missions',
    resource: 'mission',
    permission: 'missions.view',
    authorizer: 'authorizeVerificationPlanAccess',
    tenantPath: 'verification_plan.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'missions.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/verification-plans/:id/resolution-summary',
    resource: 'verification_resolution',
    permission: 'verification_plans.view',
    authorizer: 'authorizeVerificationPlanAccess',
    tenantPath: 'verification_plan.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'verification-resolution.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/verification-needs/:id/resolution',
    resource: 'verification_need',
    permission: 'verification_plans.view',
    authorizer: 'authorizeVerificationNeedAccess',
    tenantPath: 'verification_need.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'verification-resolution.ts',
  },
  {
    method: 'GET',
    path: '/api/intelligence/verification-needs/:id/resolution-history',
    resource: 'verification_need',
    permission: 'verification_plans.view',
    authorizer: 'authorizeVerificationNeedAccess',
    tenantPath: 'verification_need.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'verification-resolution.ts',
  },
  {
    method: 'POST',
    path: '/api/intelligence/verification-needs/:id/re-evaluate',
    resource: 'verification_need',
    permission: 'verification_plans.view',
    authorizer: 'authorizeVerificationNeedAccess',
    tenantPath: 'verification_need.organization_id',
    usesServiceRole: true,
    rateLimit: 'reevaluation',
    status: 'protected',
    routeFile: 'verification-resolution.ts',
  },
  // Environment — fires (authenticated reads)
  {
    method: 'GET',
    path: '/api/environment/fires/*',
    resource: 'fire_event',
    permission: 'incidents.view',
    authorizer: 'sessionOnly',
    tenantPath: 'national_scope',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'fires.ts',
  },
  {
    method: 'GET',
    path: '/api/environment/fires/events/:id/incident',
    resource: 'incident',
    permission: 'incidents.view',
    authorizer: 'sessionOnly',
    tenantPath: 'fire_event',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'incidents.ts',
  },
  {
    method: 'GET',
    path: '/api/environment/fires/events/:id/findings',
    resource: 'finding',
    permission: 'findings.view',
    authorizer: 'sessionOnly',
    tenantPath: 'fire_event',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'findings.ts',
  },
  {
    method: 'GET',
    path: '/api/environment/fires/events/:id/priority',
    resource: 'priority',
    permission: 'priorities.view',
    authorizer: 'sessionOnly',
    tenantPath: 'fire_event',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'priorities.ts',
  },
  // Operations — missions
  {
    method: 'GET',
    path: '/api/operations/missions',
    resource: 'mission',
    permission: 'missions.view',
    authorizer: 'orgListScope',
    tenantPath: 'organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'missions.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/missions/:id',
    resource: 'mission',
    permission: 'missions.view',
    authorizer: 'authorizeMissionAccess',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'missions.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/missions/:id/tasks',
    resource: 'mission_task',
    permission: 'missions.view',
    authorizer: 'authorizeMissionAccess',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'missions.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/missions/:id/evidence-requirements',
    resource: 'evidence_requirement',
    permission: 'evidence.view',
    authorizer: 'authorizeMissionAccess',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'missions.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/missions/:id/assignments',
    resource: 'mission_assignment',
    permission: 'missions.view',
    authorizer: 'authorizeMissionAccess',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'missions.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/missions/:id/{workflow}',
    resource: 'mission',
    permission: 'missions.*',
    authorizer: 'authorizeMissionWorkflowAction',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    status: 'protected',
    routeFile: 'missions.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/assignees/:type/:id/missions',
    resource: 'mission',
    permission: 'missions.view',
    authorizer: 'assigneeScope',
    tenantPath: 'assignee.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'missions.ts',
  },
  // Evidence intake
  {
    method: 'GET',
    path: '/api/operations/missions/:id/evidence',
    resource: 'evidence_submission',
    permission: 'evidence.view',
    authorizer: 'authorizeMissionAccess',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'evidence-intake.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/missions/:id/evidence-coverage',
    resource: 'evidence_submission',
    permission: 'evidence.view',
    authorizer: 'authorizeMissionAccess',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'evidence-intake.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/missions/:id/evidence-submissions',
    resource: 'evidence_submission',
    permission: 'evidence.submit',
    authorizer: 'authorizeEvidenceMissionWrite',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'evidence_create',
    status: 'protected',
    routeFile: 'evidence-intake.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/evidence-submissions/:id',
    resource: 'evidence_submission',
    permission: 'evidence.view',
    authorizer: 'authorizeEvidenceSubmissionRead',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'evidence-intake.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/evidence-submissions/:id/upload-url',
    resource: 'evidence_asset',
    permission: 'evidence.submit',
    authorizer: 'authorizeSignedUploadUrl',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    rateLimit: 'signed_url',
    status: 'protected',
    routeFile: 'evidence-intake.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/evidence-submissions/:id/confirm-upload',
    resource: 'evidence_asset',
    permission: 'evidence.submit',
    authorizer: 'authorizeEvidenceSubmissionWrite',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    rateLimit: 'upload_session',
    status: 'protected',
    routeFile: 'evidence-intake.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/evidence-submissions/:id/observations',
    resource: 'evidence_submission',
    permission: 'evidence.submit',
    authorizer: 'authorizeEvidenceSubmissionWrite',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    rateLimit: 'evidence_create',
    status: 'protected',
    routeFile: 'evidence-intake.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/evidence-submissions/:id/withdraw',
    resource: 'evidence_submission',
    permission: 'evidence.withdraw',
    authorizer: 'authorizeEvidenceSubmissionWrite',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    status: 'protected',
    routeFile: 'evidence-intake.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/tasks/:id/evidence',
    resource: 'evidence_submission',
    permission: 'evidence.view',
    authorizer: 'authorizeTaskEvidenceRead',
    tenantPath: 'task.mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'evidence-intake.ts',
  },
  // Evidence validation
  {
    method: 'GET',
    path: '/api/operations/evidence-submissions/:id/validation',
    resource: 'evidence_submission',
    permission: 'evidence.view',
    authorizer: 'authorizeEvidenceSubmissionRead',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'evidence-validation.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/evidence-submissions/:id/validation-history',
    resource: 'evidence_submission',
    permission: 'evidence.view',
    authorizer: 'authorizeEvidenceSubmissionRead',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'evidence-validation.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/evidence-submissions/:id/revalidate',
    resource: 'evidence_submission',
    permission: 'evidence.revalidate',
    authorizer: 'authorizeEvidenceValidation',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    rateLimit: 'validation',
    status: 'protected',
    routeFile: 'evidence-validation.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/missions/:id/evidence-validations',
    resource: 'evidence_submission',
    permission: 'evidence.view',
    authorizer: 'authorizeMissionAccess',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'evidence-validation.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/missions/:id/evidence-quality-summary',
    resource: 'evidence_submission',
    permission: 'evidence.view',
    authorizer: 'authorizeMissionAccess',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'evidence-validation.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/missions/:id/resolution-contributions',
    resource: 'verification_resolution',
    permission: 'verification_plans.view',
    authorizer: 'authorizeMissionAccess',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'verification-resolution.ts',
  },
  // Offline packages
  {
    method: 'GET',
    path: '/api/operations/missions/:id/offline-packages',
    resource: 'offline_mission_package',
    permission: 'offline_packages.download',
    authorizer: 'authorizeMissionAccess',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'offline-packages.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/missions/:id/offline-packages',
    resource: 'offline_mission_package',
    permission: 'offline_packages.generate',
    authorizer: 'authorizeOfflinePackageMissionAction',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'package_generate',
    status: 'protected',
    routeFile: 'offline-packages.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/offline-packages/:id',
    resource: 'offline_mission_package',
    permission: 'offline_packages.download',
    authorizer: 'authorizeOfflinePackageAccess',
    tenantPath: 'package.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'offline-packages.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/offline-packages/:id/manifest',
    resource: 'offline_mission_package',
    permission: 'offline_packages.download',
    authorizer: 'authorizeOfflinePackageAccess',
    tenantPath: 'package.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'offline-packages.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/offline-packages/:id/status',
    resource: 'offline_mission_package',
    permission: 'offline_packages.download',
    authorizer: 'authorizeOfflinePackageAccess',
    tenantPath: 'package.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'offline-packages.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/offline-packages/:id/validate',
    resource: 'offline_mission_package',
    permission: 'offline_packages.download',
    authorizer: 'authorizeOfflinePackageAccess',
    tenantPath: 'package.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'offline-packages.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/offline-packages/:id/download-url',
    resource: 'offline_mission_package',
    permission: 'offline_packages.download',
    authorizer: 'authorizeOfflinePackageAccess',
    tenantPath: 'package.organization_id',
    usesServiceRole: true,
    rateLimit: 'package_download',
    status: 'protected',
    routeFile: 'offline-packages.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/offline-packages/:id/confirm-download',
    resource: 'offline_mission_package',
    permission: 'offline_packages.download',
    authorizer: 'authorizeOfflinePackageAccess',
    tenantPath: 'package.organization_id',
    usesServiceRole: true,
    rateLimit: 'package_download',
    status: 'protected',
    routeFile: 'offline-packages.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/offline-packages/:id/revoke',
    resource: 'offline_mission_package',
    permission: 'offline_packages.revoke',
    authorizer: 'authorizeOfflinePackageAccess',
    tenantPath: 'package.organization_id',
    usesServiceRole: true,
    status: 'protected',
    routeFile: 'offline-packages.ts',
  },
  // Field sync
  {
    method: 'POST',
    path: '/api/operations/field-sync/bundles/register',
    resource: 'evidence_bundle',
    permission: 'field_sync.execute',
    authorizer: 'authorizeFieldSyncAccess',
    tenantPath: 'mission.organization_id',
    usesServiceRole: true,
    rateLimit: 'field_sync_register',
    status: 'protected',
    routeFile: 'field-sync.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/evidence-submissions/:id/upload-sessions',
    resource: 'evidence_upload_session',
    permission: 'evidence.submit',
    authorizer: 'authorizeSignedUploadUrl',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    rateLimit: 'upload_session',
    status: 'protected',
    routeFile: 'field-sync.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/evidence-submissions/:id/upload-sessions/:sid/renew-url',
    resource: 'evidence_upload_session',
    permission: 'evidence.submit',
    authorizer: 'authorizeSignedUploadUrl',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    rateLimit: 'signed_url',
    status: 'protected',
    routeFile: 'field-sync.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/evidence-submissions/:id/upload-sessions/:sid/progress',
    resource: 'evidence_upload_session',
    permission: 'evidence.submit',
    authorizer: 'authorizeEvidenceSubmissionWrite',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    rateLimit: 'sync_retry',
    status: 'protected',
    routeFile: 'field-sync.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/evidence-submissions/:id/upload-sessions/:sid',
    resource: 'evidence_upload_session',
    permission: 'evidence.view',
    authorizer: 'authorizeEvidenceSubmissionRead',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'field-sync.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/evidence-submissions/:id/requirement-links',
    resource: 'evidence_submission',
    permission: 'evidence.submit',
    authorizer: 'authorizeEvidenceSubmissionWrite',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    status: 'protected',
    routeFile: 'field-sync.ts',
  },
  {
    method: 'POST',
    path: '/api/operations/evidence-submissions/:id/finalize-intake',
    resource: 'evidence_submission',
    permission: 'evidence.submit',
    authorizer: 'authorizeEvidenceSubmissionWrite',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    status: 'protected',
    routeFile: 'field-sync.ts',
  },
  {
    method: 'GET',
    path: '/api/operations/evidence-submissions/:id/reconciliation',
    resource: 'evidence_submission',
    permission: 'evidence.view',
    authorizer: 'authorizeEvidenceSubmissionRead',
    tenantPath: 'submission.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'field-sync.ts',
  },
  // Response orchestration (8C.1.2)
  {
    method: 'GET',
    path: '/api/responses/executive-summary',
    resource: 'response_list',
    permission: 'responses.view',
    authorizer: 'authorizeResponseListScope',
    tenantPath: 'organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  {
    method: 'GET',
    path: '/api/responses',
    resource: 'response_list',
    permission: 'responses.view',
    authorizer: 'authorizeResponseListScope',
    tenantPath: 'organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  {
    method: 'GET',
    path: '/api/responses/:incidentId',
    resource: 'response_assessment',
    permission: 'responses.view',
    authorizer: 'authorizeResponseAssessmentAccess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  {
    method: 'POST',
    path: '/api/responses/:incidentId/assess',
    resource: 'response_assessment',
    permission: 'responses.assess',
    authorizer: 'authorizeResponseAssess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'reevaluation',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  {
    method: 'POST',
    path: '/api/responses/:incidentId/decisions',
    resource: 'decision_record',
    permission: 'responses.decide',
    authorizer: 'authorizeResponseDecide',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'validation',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  {
    method: 'PATCH',
    path: '/api/responses/decisions/:decisionId',
    resource: 'decision_record',
    permission: 'responses.modify',
    authorizer: 'authorizeResponseModify',
    tenantPath: 'decision.organization_id',
    usesServiceRole: true,
    rateLimit: 'validation',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  {
    method: 'POST',
    path: '/api/responses/decisions/:decisionId/approve',
    resource: 'decision_record',
    permission: 'responses.approve',
    authorizer: 'authorizeResponseApproval',
    tenantPath: 'decision.organization_id',
    usesServiceRole: true,
    rateLimit: 'validation',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  {
    method: 'POST',
    path: '/api/responses/decisions/:decisionId/reject',
    resource: 'decision_record',
    permission: 'responses.reject',
    authorizer: 'authorizeResponseReject',
    tenantPath: 'decision.organization_id',
    usesServiceRole: true,
    rateLimit: 'validation',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  {
    method: 'POST',
    path: '/api/responses/decisions/:decisionId/actions',
    resource: 'response_action',
    permission: 'response_actions.create',
    authorizer: 'authorizeResponseDecisionAccess',
    tenantPath: 'decision.organization_id',
    usesServiceRole: true,
    rateLimit: 'validation',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  {
    method: 'PATCH',
    path: '/api/responses/actions/:actionId',
    resource: 'response_action',
    permission: 'response_actions.execute',
    authorizer: 'authorizeResponseActionAccess',
    tenantPath: 'action.organization_id',
    usesServiceRole: true,
    rateLimit: 'validation',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  {
    method: 'GET',
    path: '/api/responses/:incidentId/briefing',
    resource: 'response_briefing',
    permission: 'responses.view',
    authorizer: 'authorizeResponseAssessmentAccess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  {
    method: 'GET',
    path: '/api/responses/:incidentId/closure-assessment',
    resource: 'closure_recommendation',
    permission: 'incident_closure.recommend',
    authorizer: 'authorizeClosureRecommendationAccess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  {
    method: 'GET',
    path: '/api/responses/:incidentId/history',
    resource: 'response_history',
    permission: 'responses.view',
    authorizer: 'authorizeResponseAssessmentAccess',
    tenantPath: 'incident.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'response-orchestration.ts',
  },
  // Auth (session)
  {
    method: 'GET',
    path: '/api/auth/me',
    resource: 'session',
    permission: null,
    authorizer: 'sessionOnly',
    tenantPath: 'n/a',
    usesServiceRole: false,
    status: 'protected',
    routeFile: 'auth.ts',
  },
  {
    method: 'POST',
    path: '/api/auth/active-organization',
    resource: 'membership',
    permission: null,
    authorizer: 'sessionOnly',
    tenantPath: 'membership.organization_id',
    usesServiceRole: true,
    rateLimit: 'org_switch',
    status: 'protected',
    routeFile: 'auth.ts',
  },
  {
    method: 'GET',
    path: '/api/auth/memberships',
    resource: 'membership',
    permission: null,
    authorizer: 'sessionOnly',
    tenantPath: 'membership.organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'provisioning.ts',
  },
  {
    method: 'POST',
    path: '/api/auth/invitations/accept',
    resource: 'invitation',
    permission: null,
    authorizer: 'sessionOnly',
    tenantPath: 'invitation.organization_id',
    usesServiceRole: true,
    rateLimit: 'invitation',
    status: 'protected',
    routeFile: 'provisioning.ts',
  },
  {
    method: 'GET',
    path: '/api/admin/organization/members',
    resource: 'membership',
    permission: 'memberships.manage',
    authorizer: 'orgListScope',
    tenantPath: 'organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'provisioning.ts',
  },
  {
    method: 'POST',
    path: '/api/admin/organization/invitations',
    resource: 'invitation',
    permission: 'users.invite',
    authorizer: 'orgListScope',
    tenantPath: 'organization_id',
    usesServiceRole: true,
    rateLimit: 'invitation',
    status: 'protected',
    routeFile: 'provisioning.ts',
  },
  // Executive metrics (Product Consolidation — Phase 1)
  {
    method: 'GET',
    path: '/api/executive/metrics',
    resource: 'executive_metric',
    permission: 'findings.view',
    authorizer: 'sessionOnly',
    tenantPath: 'organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'executive-metrics.ts',
  },
  {
    method: 'GET',
    path: '/api/executive/metrics/:metricId',
    resource: 'executive_metric',
    permission: 'findings.view',
    authorizer: 'sessionOnly',
    tenantPath: 'organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'executive-metrics.ts',
  },
  {
    method: 'GET',
    path: '/api/executive/data-quality-summary',
    resource: 'executive_metric',
    permission: 'findings.view',
    authorizer: 'sessionOnly',
    tenantPath: 'organization_id',
    usesServiceRole: true,
    rateLimit: 'default_read',
    status: 'protected',
    routeFile: 'executive-metrics.ts',
  },
  // Public by design
  {
    method: 'GET',
    path: '/api/health',
    resource: 'health',
    permission: null,
    authorizer: null,
    tenantPath: 'n/a',
    usesServiceRole: false,
    status: 'public-by-design',
    routeFile: 'index.ts',
  },
]

export function registryRoutesForFile(routeFile: string): OperationalRouteSpec[] {
  return OPERATIONAL_ROUTE_REGISTRY.filter((r) => r.routeFile === routeFile)
}

export function incompleteRegistryRoutes(): OperationalRouteSpec[] {
  return OPERATIONAL_ROUTE_REGISTRY.filter((r) => r.status === 'incomplete')
}

export function protectedRegistryRoutes(): OperationalRouteSpec[] {
  return OPERATIONAL_ROUTE_REGISTRY.filter((r) => r.status === 'protected')
}
