/**
 * Shared generation logic for the event registration indexes. No side effects.
 * Used by event:sync (writes) and the framework audit (checks).
 */
import { existsSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = process.cwd()
export const EVENTS_DIR = resolve(ROOT, 'src/events')
export const SERVER_EVENTS_DIR = resolve(ROOT, 'server/events')
export const MANIFESTS_INDEX = resolve(EVENTS_DIR, 'manifests.generated.ts')
export const SERVER_INDEX = resolve(SERVER_EVENTS_DIR, 'server.generated.ts')

export function pluginFolders(): string[] {
  return readdirSync(EVENTS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name !== 'specs')
    .map((d) => d.name)
    .filter((name) => existsSync(resolve(EVENTS_DIR, name, 'event.manifest.ts')))
    .sort()
}

export function folderToCamel(folder: string): string {
  return folder
    .split(/[-_]/)
    .map((w, i) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)))
    .join('')
}

export function generateManifestsIndex(): string {
  const folders = pluginFolders()
  const imports = folders
    .map((f) => `import ${folderToCamel(f)}Manifest from '@/events/${f}/event.manifest'`)
    .join('\n')
  const items = folders.map((f) => `  ${folderToCamel(f)}Manifest,`).join('\n')
  return `/**
 * AUTO-GENERATED by \`npm run event:sync\`. DO NOT EDIT BY HAND.
 *
 * Single source of manifest registration: every plugin's \`event.manifest.ts\`
 * is discovered by convention (src/events/<type>/) and listed here. Static
 * imports keep this compatible with Vite, tsx and vitest alike.
 */
import type { EnvironmentalEventManifest } from '@/modules/environmental-events/manifest/event-manifest'
${imports}

export const ALL_EVENT_MANIFESTS: EnvironmentalEventManifest[] = [
${items}
]
`
}

export function generateServerIndex(): string {
  const folders = pluginFolders().filter((f) =>
    existsSync(resolve(SERVER_EVENTS_DIR, `${f}.server.ts`)),
  )
  const imports = folders.map((f) => `import './${f}.server.js'`).join('\n')
  return `/**
 * AUTO-GENERATED by \`npm run event:sync\`. DO NOT EDIT BY HAND.
 *
 * Single source of server-side plugin wiring: every plugin's server module is
 * imported here so its repository/detector/source register into the shared
 * server registry at startup. Importing this module has the side effect of
 * registration.
 */
${imports}
`
}
