import type { Variable } from '../entities/variable'

/**
 * Variables semilla del Catálogo Nacional.
 * Ver docs/VARIABLE-CATALOG.md para descripción completa.
 */
export const SEED_VARIABLES: Variable[] = [
  {
    id: 'ndvi',
    nombre: 'Índice de Vegetación de Diferencia Normalizada',
    nombreCorto: 'NDVI',
    categoria: 'vegetacion',
    fuenteId: 'sentinel-2',
    unidad: 'índice',
    tipoValor: 'numerico',
    resolucionEspacial: '10m',
    resolucionTemporal: '16 días',
    frecuenciaActualizacion: '5 días',
    rangoNormal: { min: 0.6, max: 0.8 },
    interpretacion: 'Mayor valor = vegetación más saludable y densa',
    direccionPreferida: 'alto',
    variablesRelacionadas: ['evi', 'ndmi', 'rainfall_daily', 'temperature_anomaly'],
    usadaEnReglas: ['R-DET-001', 'R-COR-001', 'R-HIP-001'],
    categoriasHallazgo: ['vegetacion', 'compuesto'],
    umbralAlerta: -10,
    umbralCritico: -20,
    metodoBaseline: 'media_movil_30d',
    activa: true,
    version: '1.0',
  },
  {
    id: 'rainfall_daily',
    nombre: 'Precipitación diaria',
    nombreCorto: 'Lluvia',
    categoria: 'clima',
    fuenteId: 'chirps',
    unidad: 'mm',
    tipoValor: 'numerico',
    resolucionEspacial: '5.5km',
    resolucionTemporal: 'diario',
    frecuenciaActualizacion: 'diaria',
    rangoNormal: { min: 0, max: 50 },
    interpretacion: 'Milímetros de precipitación acumulada por día',
    direccionPreferida: 'neutral',
    variablesRelacionadas: ['rainfall_anomaly', 'ndvi', 'ndmi'],
    usadaEnReglas: ['R-DET-006', 'R-COR-001'],
    categoriasHallazgo: ['climatico', 'hidrologico'],
    metodoBaseline: 'estacional',
    activa: true,
    version: '1.0',
  },
  {
    id: 'rainfall_anomaly',
    nombre: 'Anomalía de precipitación',
    nombreCorto: 'Anomalía lluvia',
    categoria: 'clima',
    fuenteId: 'chirps',
    unidad: '%',
    tipoValor: 'numerico',
    resolucionEspacial: '5.5km',
    resolucionTemporal: '30 días acumulado',
    frecuenciaActualizacion: 'diaria',
    rangoNormal: { min: -15, max: 15 },
    interpretacion: 'Porcentaje de desviación de la media histórica',
    direccionPreferida: 'estable',
    variablesRelacionadas: ['rainfall_daily', 'ndvi'],
    usadaEnReglas: ['R-DET-006', 'R-DET-007', 'R-INH-004'],
    categoriasHallazgo: ['climatico', 'hidrologico', 'compuesto'],
    umbralAlerta: -30,
    umbralCritico: -50,
    metodoBaseline: 'percentil_historico',
    activa: true,
    version: '1.0',
  },
  {
    id: 'temperature',
    nombre: 'Temperatura del aire a 2m',
    nombreCorto: 'Temperatura',
    categoria: 'clima',
    fuenteId: 'openmeteo',
    unidad: '°C',
    tipoValor: 'numerico',
    resolucionEspacial: '9km',
    resolucionTemporal: 'horario',
    frecuenciaActualizacion: 'horaria',
    rangoNormal: { min: 18, max: 32 },
    interpretacion: 'Temperatura del aire a 2 metros sobre el suelo',
    direccionPreferida: 'estable',
    variablesRelacionadas: ['temperature_anomaly', 'humidity'],
    usadaEnReglas: [],
    categoriasHallazgo: ['climatico'],
    metodoBaseline: 'estacional',
    activa: true,
    version: '1.0',
  },
  {
    id: 'temperature_anomaly',
    nombre: 'Anomalía de temperatura',
    nombreCorto: 'Anomalía térmica',
    categoria: 'clima',
    fuenteId: 'era5',
    unidad: '°C',
    tipoValor: 'numerico',
    resolucionEspacial: '9km',
    resolucionTemporal: 'diario',
    frecuenciaActualizacion: 'diaria',
    rangoNormal: { min: -2, max: 2 },
    interpretacion: 'Desviación de la media histórica — positivo = más caliente',
    direccionPreferida: 'estable',
    variablesRelacionadas: ['temperature', 'rainfall_anomaly', 'ndvi'],
    usadaEnReglas: ['R-DET-005', 'R-COR-001'],
    categoriasHallazgo: ['climatico', 'compuesto'],
    umbralAlerta: 2,
    umbralCritico: 4,
    metodoBaseline: 'percentil_historico',
    activa: true,
    version: '1.0',
  },
  {
    id: 'fire_radiative_power',
    nombre: 'Potencia radiativa de fuego',
    nombreCorto: 'FRP',
    categoria: 'incendio',
    fuenteId: 'nasa-firms',
    unidad: 'MW',
    tipoValor: 'numerico',
    resolucionEspacial: '1km',
    resolucionTemporal: 'por detección',
    frecuenciaActualizacion: '3 horas',
    rangoNormal: { min: 0, max: 0 },
    interpretacion: 'Intensidad del foco de calor — 0 = sin detección',
    direccionPreferida: 'bajo',
    variablesRelacionadas: ['fire_count', 'temperature_anomaly', 'ndvi'],
    usadaEnReglas: ['R-DET-003', 'R-DET-004'],
    categoriasHallazgo: ['incendio'],
    umbralAlerta: 0,
    umbralCritico: 50,
    metodoBaseline: 'media_movil_30d',
    activa: true,
    version: '1.0',
  },
]

export function getVariableById(id: string): Variable | undefined {
  return SEED_VARIABLES.find((v) => v.id === id)
}

export function getVariablesByCategory(categoria: Variable['categoria']): Variable[] {
  return SEED_VARIABLES.filter((v) => v.categoria === categoria)
}
